import 'package:flutter/material.dart';

class LanguageManager {
  static String currentLanguage = 'en'; // 'en' یا 'fa'

  static final Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Ninja Trips',
      'home': 'Home',
      'search': 'Search',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'myFavorites': 'My Favorites',
      'searchTrips': 'Search Trips',
      'myProfile': 'My Profile',
      'noFavorites': 'No favorites yet',
      'exploreTrips': 'Explore Trips',
      'tripDetails': 'Trip Details',
      'description': 'Description',
      'features': 'Features',
      'bookNow': 'Book Now',
      'settings': 'Settings',
      'categories': 'Categories',
      'popularTrips': 'Popular Trips',
      'allTrips': 'All Trips',
      'seeAll': 'See All',
      'welcomeTitle': 'Hello, Traveler!',
      'welcomeSubtitle': 'Ready for your next adventure?',
      'theme': 'Theme',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'systemTheme': 'System Theme',
      'preferences': 'Preferences',
      'pushNotifications': 'Push Notifications',
      'currency': 'Currency',
      'selectCurrency': 'Select Currency',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'termsConditions': 'Terms & Conditions',
      'privacyPolicy': 'Privacy Policy',
      'language': 'Language',
      'english': 'English',
      'persian': 'Persian',
      'all': 'All',
      'beach': 'Beach',
      'mountain': 'Mountain',
      'city': 'City',
      'desert': 'Desert',
      'island': 'Island',
      'historical': 'Historical',
      'searchPlaceholder': 'Search destinations...',
      'trips': 'Trips',
      'reviews': 'Reviews',
      'countries': 'Countries',
      'bookingHistory': 'Booking History',
      'logout': 'Logout',
      'ski': 'Ski',
      'usd': 'USD - US Dollar',
      'eur': 'EUR - Euro',
      'gbp': 'GBP - British Pound',
      'noTripsFound': 'No trips found',
      'tryDifferentCategory': 'Try selecting a different category',
    },
    'fa': {
      'appTitle': 'سفرهای نینجا',
      'home': 'خانه',
      'search': 'جستجو',
      'favorites': 'علاقه‌مندی‌ها',
      'profile': 'پروفایل',
      'myFavorites': 'علاقه‌مندی‌های من',
      'searchTrips': 'جستجوی سفرها',
      'myProfile': 'پروفایل من',
      'noFavorites': 'هنوز مورد علاقه‌ای ندارید',
      'exploreTrips': 'کشف سفرها',
      'tripDetails': 'جزئیات سفر',
      'description': 'توضیحات',
      'features': 'ویژگی‌ها',
      'bookNow': 'رزرو کنید',
      'settings': 'تنظیمات',
      'categories': 'دسته‌بندی‌ها',
      'popularTrips': 'سفرهای محبوب',
      'allTrips': 'همه سفرها',
      'seeAll': 'مشاهده همه',
      'welcomeTitle': 'سلام، مسافر!',
      'welcomeSubtitle': 'آماده برای ماجراجویی بعدی؟',
      'theme': 'تم',
      'lightMode': 'حالت روشن',
      'darkMode': 'حالت تاریک',
      'systemTheme': 'تم سیستم',
      'preferences': 'ترجیحات',
      'pushNotifications': 'اعلان‌ها',
      'currency': 'واحد پول',
      'selectCurrency': 'انتخاب واحد پول',
      'support': 'پشتیبانی',
      'helpCenter': 'مرکز کمک',
      'termsConditions': 'قوانین و مقررات',
      'privacyPolicy': 'حریم خصوصی',
      'language': 'زبان',
      'english': 'انگلیسی',
      'persian': 'فارسی',
      'all': 'همه',
      'beach': 'ساحل',
      'mountain': 'کوهستان',
      'city': 'شهری',
      'desert': 'بیابان',
      'island': 'جزیره',
      'historical': 'تاریخی',
      'searchPlaceholder': 'جستجوی مقاصد...',
      'trips': 'سفرها',
      'reviews': 'نظرات',
      'countries': 'کشورها',
      'bookingHistory': 'تاریخچه رزرو',
      'logout': 'خروج',
      'ski': 'اسکی',
      'usd': 'دلار آمریکا',
      'eur': 'یورو',
      'gbp': 'پوند انگلیس',
      'noTripsFound': 'هیچ سفری یافت نشد',
      'tryDifferentCategory': 'دسته‌بندی دیگری را انتخاب کنید',
    },
  };

  static String translate(String key) {
    return translations[currentLanguage]![key] ?? key;
  }

  static void changeLanguage(String lang) {
    currentLanguage = lang;
  }
}