import 'package:flutter/material.dart';

class LanguageManager {
  static String currentLanguage = 'en'; // 'en' یا 'fa'

  static final Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Ninja Trips',
      'home': 'Home',
      'search': 'Search',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'myFavorites': 'My Favorites',
      'noFavorites': 'No favorites yet',
      'noFavoritesMsg': 'Tap the heart icon on any trip to save it here',
      'exploreTrips': 'Explore Trips',
      'searchTrips': 'Search Trips',
      'myProfile': 'My Profile',
      'editProfile': 'Edit Profile',
      'saveChanges': 'Save Changes',
      'profileUpdated': 'Profile updated successfully',
      'tripDetails': 'Trip Details',
      'description': 'Description',
      'features': 'Features',
      'bookNow': 'Book Now',
      'bookTrip': 'Book Trip',
      'confirmBooking': 'Confirm Booking',
      'bookingConfirmed': 'Booking Confirmed!',
      'bookingConfirmedMsg': 'Your trip has been booked successfully. Have a great trip!',
      'cancelBooking': 'Cancel Booking',
      'cancelBookingMsg': 'Are you sure you want to cancel this booking?',
      'travelerInfo': 'Traveler Information',
      'fullName': 'Full Name',
      'email': 'Email Address',
      'travelDate': 'Travel Date',
      'numberOfTravelers': 'Number of Travelers',
      'pricePerPerson': 'Price per person',
      'travelers': 'Travelers',
      'totalPrice': 'Total Price',
      'settings': 'Settings',
      'categories': 'Categories',
      'popularTrips': 'Popular Trips',
      'allTrips': 'All Trips',
      'seeAll': 'See All',
      'welcomeTitle': 'Hello, Traveler!',
      'welcomeSubtitle': 'Ready for your next adventure?',
      'theme': 'Theme',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'systemTheme': 'System Theme',
      'preferences': 'Preferences',
      'pushNotifications': 'Push Notifications',
      'currency': 'Currency',
      'selectCurrency': 'Select Currency',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'termsConditions': 'Terms & Conditions',
      'privacyPolicy': 'Privacy Policy',
      'language': 'Language',
      'english': 'English',
      'persian': 'Persian (فارسی)',
      'all': 'All',
      'beach': 'Beach',
      'mountain': 'Mountain',
      'city': 'City',
      'desert': 'Desert',
      'island': 'Island',
      'historical': 'Historical',
      'searchPlaceholder': 'Search destinations...',
      'trips': 'Trips',
      'reviews': 'Reviews',
      'countries': 'Countries',
      'bookings': 'Bookings',
      'bookingHistory': 'Booking History',
      'noBookings': 'No bookings yet',
      'noBookingsMsg': 'Book a trip to see your history here',
      'confirmed': 'Confirmed',
      'cancelled': 'Cancelled',
      'pending': 'Pending',
      'logout': 'Logout',
      'logoutConfirm': 'Are you sure you want to logout?',
      'loggedOut': 'You have been logged out',
      'cancel': 'Cancel',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'ski': 'Ski',
      'popular': 'Popular',
      'results': 'results',
      'saved': 'saved',
      'nameRequired': 'Please enter your name',
      'emailRequired': 'Please enter your email',
      'emailInvalid': 'Please enter a valid email',
      'perPerson': 'person',
      'noTripsFound': 'No trips found',
      'tryDifferentCategory': 'Try a different search term',
    },
    'fa': {
      'appTitle': 'سفرهای نینجا',
      'home': 'خانه',
      'search': 'جستجو',
      'favorites': 'علاقه‌مندی‌ها',
      'profile': 'پروفایل',
      'myFavorites': 'علاقه‌مندی‌های من',
      'noFavorites': 'هنوز موردی ذخیره نشده',
      'noFavoritesMsg': 'روی آیکون قلب هر سفر بزنید تا اینجا ذخیره شود',
      'exploreTrips': 'کشف سفرها',
      'searchTrips': 'جستجوی سفرها',
      'myProfile': 'پروفایل من',
      'editProfile': 'ویرایش پروفایل',
      'saveChanges': 'ذخیره تغییرات',
      'profileUpdated': 'پروفایل با موفقیت به‌روزرسانی شد',
      'tripDetails': 'جزئیات سفر',
      'description': 'توضیحات',
      'features': 'ویژگی‌ها',
      'bookNow': 'رزرو کنید',
      'bookTrip': 'رزرو سفر',
      'confirmBooking': 'تأیید رزرو',
      'bookingConfirmed': 'رزرو تأیید شد!',
      'bookingConfirmedMsg': 'سفر شما با موفقیت رزرو شد. سفر خوبی داشته باشید!',
      'cancelBooking': 'لغو رزرو',
      'cancelBookingMsg': 'آیا مطمئن هستید که می‌خواهید این رزرو را لغو کنید؟',
      'travelerInfo': 'اطلاعات مسافر',
      'fullName': 'نام کامل',
      'email': 'آدرس ایمیل',
      'travelDate': 'تاریخ سفر',
      'numberOfTravelers': 'تعداد مسافران',
      'pricePerPerson': 'قیمت به ازای هر نفر',
      'travelers': 'مسافران',
      'totalPrice': 'قیمت کل',
      'settings': 'تنظیمات',
      'categories': 'دسته‌بندی‌ها',
      'popularTrips': 'سفرهای محبوب',
      'allTrips': 'همه سفرها',
      'seeAll': 'مشاهده همه',
      'welcomeTitle': 'سلام، مسافر!',
      'welcomeSubtitle': 'آماده برای ماجراجویی بعدی؟',
      'theme': 'تم',
      'lightMode': 'حالت روشن',
      'darkMode': 'حالت تاریک',
      'systemTheme': 'تم سیستم',
      'preferences': 'ترجیحات',
      'pushNotifications': 'اعلان‌های فشاری',
      'currency': 'واحد پول',
      'selectCurrency': 'انتخاب واحد پول',
      'support': 'پشتیبانی',
      'helpCenter': 'مرکز کمک',
      'termsConditions': 'قوانین و مقررات',
      'privacyPolicy': 'حریم خصوصی',
      'language': 'زبان',
      'english': 'انگلیسی (English)',
      'persian': 'فارسی',
      'all': 'همه',
      'beach': 'ساحل',
      'mountain': 'کوهستان',
      'city': 'شهری',
      'desert': 'بیابان',
      'island': 'جزیره',
      'historical': 'تاریخی',
      'searchPlaceholder': 'جستجوی مقاصد...',
      'trips': 'سفرها',
      'reviews': 'نظرات',
      'countries': 'کشورها',
      'bookings': 'رزروها',
      'bookingHistory': 'تاریخچه رزرو',
      'noBookings': 'هیچ رزروی یافت نشد',
      'noBookingsMsg': 'یک سفر رزرو کنید تا اینجا نمایش داده شود',
      'confirmed': 'تأیید شده',
      'cancelled': 'لغو شده',
      'pending': 'در انتظار',
      'logout': 'خروج',
      'logoutConfirm': 'آیا مطمئن هستید که می‌خواهید خارج شوید؟',
      'loggedOut': 'از حساب خود خارج شدید',
      'cancel': 'انصراف',
      'done': 'تمام',
      'yes': 'بله',
      'no': 'خیر',
      'ski': 'اسکی',
      'popular': 'محبوب',
      'results': 'نتیجه',
      'saved': 'ذخیره شده',
      'nameRequired': 'لطفاً نام خود را وارد کنید',
      'emailRequired': 'لطفاً ایمیل خود را وارد کنید',
      'emailInvalid': 'لطفاً یک ایمیل معتبر وارد کنید',
      'perPerson': 'نفر',
      'noTripsFound': 'هیچ سفری یافت نشد',
      'tryDifferentCategory': 'کلمه جستجوی دیگری امتحان کنید',
    },
  };

  static String translate(String key) {
    return translations[currentLanguage]![key] ?? key;
  }

  static void changeLanguage(String lang) {
    currentLanguage = lang;
  }
}